server:
  port: 8766

#eureka:
#  instance:
#    hostname : localhost
#  client :
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone:
#        http://$(eureka.instance.hostname):$(server.port)/eureka/
spring:
  rabbitmq:
    host: 192.168.112.170
    port: 5672
    username: admin
    password: 123456


#日志配置
logging :
#  path : /Users/gaihongwei/tools/eclipse/workspace/zmj/logs
  file : logs/info.log
  level :
    root: INFO
  pattern :
    console : "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file : "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
