server:
  port: 8086
spring:
  base:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.112.36:3306?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 58test
  future:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.200.86:3306?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
  regular:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.112.17:3306?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: appuser
      password: 976xmX5kKuRNjnIy
mybatis:
  type-aliases-package: com.mutest.model
  mapper-locations: classpath:/mappers/*.xml

files:
  path: ${file-path:d:/files}
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/mutest.log
  maxsize: 30MB
