server:
  port: 10090

spring:
  application:
    name: SPRING-BOOT-ZMJPROJECT01
  base:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  testali:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://rm-gs523r33n289871n3.mysql.singapore.rds.aliyuncs.com?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: bl_admin_rw
      password: sHl#srOEHsT^Zcl9gv1qm6KmFilL
  test:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      #dev1环境的数据库
#      jdbc-url: jdbc:mysql://rm-gs5da3x946bp408j8.mysql.singapore.rds.aliyuncs.com:3306?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#      username: bl_admin_rw
#      password: iIrWRquy0kx2DnOs
      #hpx-test(aws环境的数据库)
      jdbc-url: jdbc:mysql://locklevel-mysql-test1.cluster-cwgnjbpmvvmh.ap-southeast-1.rds.amazonaws.com:3306?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: lltest1_master_rw
      password: +vfxrhplu+xy!yc@jr*wz$6^b&16#4av
  data:
    elasticsearch:
#      cluster-name: myes
      cluster-nodes: localhost:9200

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
#    pool:
#      max-active: 100
#      max-idle: 10
#      max-wait: 100000
#    timeout: 0
  kafka:
    bootstrap-servers: 127.0.0.1:9092 #指定kafka server的地址，集群配多个，中间，逗号隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      ack: 1
      max-block-ms: 6000
      batch-size: 4096
      linger-ms: 1
      buffer-memory: 40960
      max-request-size: 1048576
      compression-type: none
    consumer:
      group-id: consumer_group1 #群组ID
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      atuo-offset-reset: earliest
      session-timeout-ms: 15000
      auto-coomit-interval-ms: 100

socket:
  config:
#    url: wss://www-demo.manniwd.com/v1/np/ws
#    url: ws://www-dev1.tfbeee.shop/v1/np/ws
#    url: wss://np-dev1.tfbeee.com/v1/np/ws
#    url: wss://www-demo.hpx.today/v1/np/ws
#    url: ws://localhost:8081/websocket/test
#    url: wss://ws.chimchim.top
#    url: ws://192.168.216.163:8651/v1/np/ws
#    url: wss://app.913139.me/v1/np/ws
#    币王生产
#    url: wss://appws.chuciyishu.com/

#    测试pusher
#    url: ws://ws-test1.tfbeee.shop/
#    测试行情
#    url: ws://www-test1.tfbeee.shop/v1/np/ws

#    榴莲模拟pusher
#    url: wss://ws.ullucky.org/
#    榴莲模拟行情
#    url: wss://app.ullucky.org/v1/np/ws

#    币晟生产
    url: wss://x.czqun.com/v1/np/ws

## Mybatis 连接
mybatis :
  typeAliasesPackage : com.zmj.demo.domain
  mapperLocations : classpath:mapper/*.xml