#服务器配置
server:
  port: 19111

## 数据源配置
spring :
  application:
    name: SPRING-BOOT-ZMJPROJECT
  base:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.112.36:3306?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 58test
  future:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.200.86:3306?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
  regular:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.112.17:3306?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: appuser
      password: 976xmX5kKuRNjnIy

web3j:
  clientAddress: http://192.168.112.214:8545


## Mybatis 配置
mybatis :
  typeAliasesPackage : com.zmj.domain
  mapperLocations : classpath:mapper/*.xml

#日志配置
#logging :
##  path : /Users/gaihongwei/tools/eclipse/workspace/zmj/logs
#  file : logs/info.log
#  level :
#    root: INFO
#  pattern :
#    console : "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
#    file : "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"



