server:
  port: 8002
#  设置服务名
spring:
  application:
    name: websocket-client
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
socket:
  config:
    url: wss://np-dev1.tfbeee.com/v1/np/ws
#    url: ws://localhost:8081/websocket/test
#    url: wss://ws.chimchim.top
#    url: ws://192.168.216.163:8651/v1/np/ws